/* EJERCICIO 1*/

DROP TABLE EJEMPLO;

CREATE TABLE  EJEMPLO 
    (NIF      VARCHAR2(10)	NOT NULL,
	 NOMBRE   VARCHAR2(30)  CONSTRAINT EJE_NOM_NN NOT NULL);
  
INSERT INTO EJEMPLO VALUES ('45222111-A', 'EIDER');
/* SIN PROBLEMAS */

INSERT INTO EJEMPLO VALUES ('45222111-A', NULL); 
INSERT INTO EJEMPLO VALUES ('45222111-A', ''); 
/* ERROR en línea 1:
ORA-01400: no se puede realizar una inserción NULL en ("EIDER"."EJEMPLO"."NOMBRE")  */


INSERT INTO EJEMPLO VALUES (NULL,'PEPE');
INSERT INTO EJEMPLO VALUES ('','PEPE');
/*ORA-01400: no se puede realizar una inserción NULL en ("EVA"."EJEMPLO"."IF") */

INSERT INTO EJEMPLO (NOMBRE) VALUES ('PEPE');

/* EJERCICIO 2 */

DROP TABLE EJEMPLO1_U;

CREATE  TABLE   EJEMPLO1_U 
	(DNI 	VARCHAR2(10) , 
	 NOMBRE	VARCHAR2(30) CONSTRAINT EJ1_NOM_UK UNIQUE, 
	 EDAD 	NUMBER(2) ); 

INSERT INTO  EJEMPLO1_U  VALUES ('11111', 'PEPA', 20); 
INSERT INTO  EJEMPLO1_U  VALUES ('11112', 'PEPA', 21); 
/* ERROR en línea 1:
ORA-00001: restricción única (EVA.EJ1_NOM_UK) violada */


DROP TABLE EJEMPLO2_U;

CREATE   TABLE   EJEMPLO2_U
 (DNI         VARCHAR2(10),
  NOMBRE      VARCHAR2(30) , 
  EDAD        NUMBER(2) , 
  CONSTRAINT  EJ2_NOMEDA_UK UNIQUE(NOMBRE,EDAD));

INSERT INTO  EJEMPLO2_U VALUES ('11112', 'PEPA', 21);
INSERT INTO  EJEMPLO2_U VALUES ('11113', 'PEPA', 22); 
INSERT INTO  EJEMPLO2_U VALUES ('11114', 'PEPA', 22);
/* ERROR en línea 1:
ORA-00001: restricción única (EVA.EJ2_NOMEDA_UK) violada */

/* EJERCICIO 3 */

DROP TABLE EJEMPLO1;

CREATE  TABLE  EJEMPLO1 
(	DNI 	VARCHAR2(10) NOT NULL, 
	NOMBRE 	VARCHAR2(30) NOT NULL, 	
	EDAD 	NUMBER(2), 
	FECHA 	DATE 	     DEFAULT SYSDATE);

INSERT  INTO EJEMPLO1(DNI, NOMBRE, EDAD) VALUES('1234','PEPA',21);

SELECT    * FROM   EJEMPLO1;
INSERT  INTO EJEMPLO1 VALUES('1234','PEPA',21, '30/04/14');
SELECT    * FROM   EJEMPLO1;

DROP TABLE EJEMPLO2;

CREATE  TABLE  EJEMPLO2 
(	DNI 	VARCHAR2(10),
	NOMBRE 	VARCHAR2(30) 	DEFAULT 'No definido',
	USUARIO NUMBER			DEFAULT UID );

INSERT   INTO EJEMPLO2 (DNI) VALUES ('1111');
SELECT   *   FROM EJEMPLO2;


/*EJERCICIO 4*/

DROP TABLE BLOQUESPISOS;

/* Restricción definida a nivel de tabla con nombre. */

CREATE TABLE BLOQUESPISOS (
	CALLE VARCHAR2(30), 
	NUMERO NUMBER(3),
	PISO NUMBER(2),
	PUERTA CHAR,
	CODIGO_POSTAL NUMBER(5),
	METROS NUMBER(5),
	COMENTARIOS VARCHAR2(60),
	COD_ZONA NUMBER(3),
	DNI VARCHAR2(10),
	CONSTRAINT BLO_CNPP_PK PRIMARY KEY(calle, numero,  piso, puerta));


/* Restricción definida a nivel de tabla sin nombre. */

CREATE TABLE BLOQUESPISOS (
	CALLE VARCHAR2(30) ,
	NUMERO NUMBER(3)  ,
	PISO NUMBER(2) ,
	PUERTA CHAR,
	CODIGO_POSTAL NUMBER(5),
	METROS NUMBER(5),
	COMENTARIOS VARCHAR2(60),
	COD_ZONA NUMBER(2),
	DNI VARCHAR2(10),
	PRIMARY KEY (calle, numero,  piso, puerta));


DROP TABLE ZONAS;

/* Restricción definida a nivel de columna con nombre. */

CREATE TABLE   ZONAS (
	COD_ZONA	NUMBER(3)   CONSTRAINT zonas_cod_pk  PRIMARY KEY,
    NOMBREZONA 	VARCHAR2(15) NOT NULL, 
    MASDATOS 	VARCHAR2(60));

/* Restricción definida a nivel de columna sin nombre. */

CREATE TABLE   ZONAS (
	COD_ZONA	NUMBER(3)    PRIMARY KEY,
    NOMBREZONA 	VARCHAR2(20) NOT NULL, 
    MASDATOS 	VARCHAR2(50));

/* Restricción definida a nivel de tabla con nombre. */

CREATE TABLE   ZONAS (
	COD_ZONA	NUMBER(3),
    NOMBREZONA 	VARCHAR2(15) NOT NULL, 
    MASDATOS 	VARCHAR2(60),
    CONSTRAINT ZON_COD_PK PRIMARY KEY (COD_ZONA));

/* Restricción definida a nivel de tabla sin nombre. */

CREATE TABLE   ZONAS (
	COD_ZONA	NUMBER(3),
    NOMBREZONA 	VARCHAR2(15) NOT NULL, 
    MASDATOS 	VARCHAR2(60),
    PRIMARY KEY (COD_ZONA));
	
	
DESCRIBE BLOQUESPISOS;
DESCRIBE ZONAS;

/* EJERCICIO 5 */

DROP TABLE ALUMNOS;

CREATE TABLE ALUMNOS(
	DNI 	VARCHAR2(10) CONSTRAINT ALU_DNI_PK 	PRIMARY KEY,	
	NOMBRE 	VARCHAR2(30) NOT NULL  CONSTRAINT 	ALU_NOM_CK  CHECK (NOMBRE=UPPER(NOMBRE)), 
	EDAD 	NUMBER(2)    CONSTRAINT ALU_EDA_CK 	CHECK (EDAD BETWEEN 5 AND 20),
	CURSO 	NUMBER       CONSTRAINT 	ALU_CUR_CK  CHECK (CURSO IN(1,2,3)));
	

INSERT   INTO   ALUMNOS VALUES('1111','Pepe',4,1);
INSERT   INTO   ALUMNOS VALUES('1111','PEPE',4,1);
INSERT   INTO   ALUMNOS VALUES('1112','PEPE',10,2);
INSERT   INTO   ALUMNOS VALUES('1113','MARIA',32,2);
INSERT   INTO   ALUMNOS VALUES('2222','MARIA',12,5);
INSERT   INTO   ALUMNOS VALUES('2224','MARiA',22,3);


/* EJERCICIO 6 */

DROP TABLE PERSONAS;
DROP TABLE PROVINCIAS;

CREATE    TABLE    PROVINCIAS 
(COD_PROV 	NUMBER(2) CONSTRAINT PROV_COD_PK PRIMARY KEY, 
 NOM_PROV 	VARCHAR2(15));


/* Creo la tabla con la restricción FK a nivel de columna, con nombre y sin nombre */

CREATE TABLE    PERSONAS (
 DNI 	    NUMBER(8) CONSTRAINT PER_DNI_PK	PRIMARY KEY,
 NOMBRE 	VARCHAR2(15), 
 DIRECCION 	VARCHAR2(25),
 POBLACION 	VARCHAR2(20),
 COD_PROV 	NUMBER(2)  REFERENCES PROVINCIAS);


CREATE TABLE    PERSONAS (
 DNI 	    NUMBER(8) CONSTRAINT PER_DNI__PK	PRIMARY KEY,
 NOMBRE 	VARCHAR2(15), 
 DIRECCION 	VARCHAR2(25),
 POBLACION 	VARCHAR2(20),
 COD_PROV 	NUMBER(2) CONSTRAINT PERS_COD_FK REFERENCES PROVINCIAS);


/*Creo la tabla con la restricción FK a nivel de tabla, con nombre y sin nombre */

DROP TABLE PERSONAS;

CREATE  TABLE  PERSONAS (
	DNI 		NUMBER(8) CONSTRAINT PER_DNI_PK	PRIMARY KEY, 
	NOMBRE 		VARCHAR2(15), 
	DIRECCION 	VARCHAR2(25), 
	POBLACION 	VARCHAR2(20),
	COD_PROV 	NUMBER(2),
	FOREIGN KEY	(COD_PROV) 	REFERENCES PROVINCIAS);

CREATE  TABLE  PERSONAS (
	DNI 		NUMBER(8) CONSTRAINT PE_DNI_PK	PRIMARY KEY, 
	NOMBRE 		VARCHAR2(15), 
	DIRECCION 	VARCHAR2(25), 
	POBLACION 	VARCHAR2(20),
	COD_PROV 	NUMBER(2),
	CONSTRAINT PER_CODP_FK 	FOREIGN KEY(COD_PROV) REFERENCES PROVINCIAS);




INSERT INTO PROVINCIAS VALUES(6, 'BADAJOZ');
INSERT INTO PROVINCIAS VALUES(28, 'MADRID');
INSERT INTO PROVINCIAS VALUES(30, 'ALAVA');
INSERT INTO PERSONAS VALUES(1111,'Juan','Las Peñas 16','Don Benito',6);
INSERT INTO PERSONAS VALUES(2222,'María','Alcalá 155', 'Madrid',28);

SELECT   *   FROM PROVINCIAS;
SELECT   *   FROM PERSONAS;

DROP TABLE PROVINCIAS;

/* ERROR en línea 1:
ORA-02449: claves únicas/primarias en la tabla referidas por claves ajenas */

DELETE FROM PROVINCIAS   WHERE    COD_PROV=28;
/* ERROR en línea 1:
ORA-02292: restricción de integridad (EVA.PER_COD_FK) violada - registro secundario encontrado */

DELETE FROM PROVINCIAS   WHERE    COD_PROV=30;
/*1 fila suprimida. */

SELECT   *   FROM PROVINCIAS;
SELECT   *   FROM PERSONAS;



/* Creamos de nuevo la tabla con la restricción ON DELETE CASCADE*/

DROP TABLE PERSONAS;

CREATE TABLE PERSONAS (
	DNI		    NUMBER(8) CONSTRAINT PERS_DNI_PK	PRIMARY KEY,
	NOMBRE 		VARCHAR2(15), 
	DIRECCION 	VARCHAR2(25), 
	POBLACION 	VARCHAR2(20),
	COD_PROV 	NUMBER(2) ,
	FOREIGN KEY (COD_PROV) REFERENCES PROVINCIAS ON DELETE CASCADE);

INSERT INTO PERSONAS VALUES(1111,'Juan','Las Peñas 16','Don Benito',6);
INSERT INTO PERSONAS VALUES(2222,'María','Alcalá 155', 'Madrid',28);

DELETE   PROVINCIAS   WHERE    COD_PROV=28;

SELECT   *   FROM PROVINCIAS;
SELECT   *   FROM PERSONAS;

/* Creamos de nuevo la tabla con la restricción ON DELETE SET NULL*/
DROP TABLE PERSONAS;

CREATE TABLE PERSONAS (
	DNI		    NUMBER(8) CONSTRAINT PERS_DNI_PK	PRIMARY KEY,
	NOMBRE 		VARCHAR2(15), 
	DIRECCION 	VARCHAR2(25), 
	POBLACION 	VARCHAR2(20),
	COD_PROV 	NUMBER(2) ,
	FOREIGN KEY (COD_PROV) REFERENCES PROVINCIAS ON DELETE SET NULL);
	
INSERT INTO PROVINCIAS VALUES(28, 'MADRID');	
INSERT INTO PERSONAS VALUES(1111,'Juan','Las Peñas 16','Don Benito',6);
INSERT INTO PERSONAS VALUES(2222,'María','Alcalá 155', 'Madrid',28);

DELETE   PROVINCIAS   WHERE    COD_PROV=28;

SELECT   *   FROM PROVINCIAS;
SELECT   *   FROM PERSONAS;

/* EJERCICIO 7 */

DROP TABLE ALUMNOS_AS;

CREATE   TABLE   ALUMNOS_AS 
AS
SELECT *  
FROM  ALUMNOS;

DESC   ALUMNOS_AS;
SELECT * FROM ALUMNOS_AS;

DROP TABLE ALUMNOS_AS;

CREATE TABLE ALUMNOS_AS (COL1, COL2, COL3, COL4) 
AS 
SELECT * 
FROM ALUMNOS
WHERE CURSO=1;

DESC   ALUMNOS_AS;
SELECT * FROM ALUMNOS_AS;

/* EJERCICIO 8 */

DROP TABLE PROVINCIAS ;
/* ERROR en línea 1:
ORA-02449: claves únicas/primarias en la tabla referidas por claves ajenas */

DROP TABLE PROVINCIAS CASCADE CONSTRAINTS; 
/* Tabla  borrada. */

/* EJERCICIO 9 */

DROP TABLE ALUMNOS;

CREATE TABLE ALUMNOS(
	DNI 	VARCHAR2(10) CONSTRAINT ALU_DNI_PK 	PRIMARY KEY,	
	NOMBRE 	VARCHAR2(30) NOT NULL  CONSTRAINT 	ALU_NOM_CK  CHECK (NOMBRE=UPPER(NOMBRE)), 
	EDAD 	NUMBER(2)    CONSTRAINT ALU_EDA_CK 	CHECK (EDAD BETWEEN 5 AND 20),
	CURSO 	NUMBER       CONSTRAINT 	ALU_CUR_CK  CHECK (CURSO IN(1,2,3)));
	

INSERT   INTO   ALUMNOS VALUES('1111','PEPE',6,1);
INSERT   INTO   ALUMNOS VALUES('1112','LUIS',7,1);
INSERT   INTO   ALUMNOS VALUES('1114','EVA',10,2);
INSERT   INTO   ALUMNOS VALUES('1113','MARIA',12,2);
INSERT   INTO   ALUMNOS VALUES('2222','NEREA',12,2);
INSERT   INTO   ALUMNOS VALUES('2224','JUAN',20,3);


SELECT * FROM ALUMNOS;

ALTER TABLE ALUMNOS ADD(SEXO  CHAR NOT NULL, IMPORTE NUMBER(4));  

/*ERROR en línea 1:
ORA-01758: la tabla debe estar vacía para agregar la columna (NOT NULL)  obligatoria*/

DESCRIBE ALUMNOS;  
SELECT * FROM ALUMNOS;

ALTER TABLE ALUMNOS ADD(SEXO  CHAR default 'H' , IMPORTE NUMBER(4)); 
ALTER TABLE ALUMNOS MODIFY( SEXO CHAR NOT NULL);

/* ERROR en línea 1:
ORA-02296: no se puede activar (EVA.) - se han encontrado valores nulos */

ALTER TABLE ALUMNOS MODIFY ( NOMBRE VARCHAR2(3), IMPORTE DEFAULT 0);

/* ERROR en línea 1:
ORA-01441: no se puede reducir la longitud de la columna porque algún valor es demasiado grande */

ALTER TABLE ALUMNOS MODIFY ( IMPORTE DEFAULT 0); 

INSERT INTO ALUMNOS(DNI,NOMBRE,EDAD,CURSO,SEXO) VALUES('1144','ANA',10,2,'M');
INSERT INTO ALUMNOS VALUES('1145','ANA',10,2,'M',100);
SELECT * FROM ALUMNOS;

/* EJERCICIO 10 */

ALTER TABLE ALUMNOS DROP (EDAD);
ALTER TABLE ALUMNOS DROP COLUMN EDAD;

ALTER TABLE ALUMNOS ADD (FECHA_NAC DATE, FECHA_ALTA DATE);

ALTER TABLE ALUMNOS RENAME COLUMN IMPORTE TO TASAS;

ALTER TABLE ALUMNOS ADD CONSTRAINT ALU_FEC_CK CHECK (FECHA_NAC < FECHA_ALTA);

ALTER TABLE ALUMNOS DROP(FECHA_NAC);
/* ERROR en línea 1:
ORA-12991: se hace referencia a la columna en una restricción de multicolumna */

ALTER TABLE ALUMNOS DROP(FECHA_NAC) CASCADE CONSTRAINTS;
