/* OPERADORES */

/* Ejemplo de Aplicación 1 */

CREATE TABLE NOTAS_ALUMNOS
(
  NOMBRE_ALUMNO    VARCHAR2(25) PRIMARY KEY,
  NOTA1 NUMBER(2),
  NOTA2 NUMBER(2),
  NOTA3 NUMBER(2));


INSERT INTO NOTAS_ALUMNOS VALUES('Alcalde García, Elena', 5,5,5);
INSERT INTO NOTAS_ALUMNOS VALUES('Benito Martín, Luis', 7,6,8);
INSERT INTO NOTAS_ALUMNOS VALUES('Casas Martinez, Manuel', 7,5,5);
INSERT INTO NOTAS_ALUMNOS VALUES('Corregidor Sanchez,Ana',6,9,8);
COMMIT;


SELECT   NOMBRE_ALUMNO AS Nombre_Alumno,
ROUND((NOTA1+NOTA2+NOTA3)/3,2)  AS "Nota Media"
FROM NOTAS_ALUMNOS;

/* Ejemplo de Aplicación 2 */

SELECT   APELLIDO,  SALARIO,  DEPT_NO 
FROM     EMPLE
WHERE   (SALARIO > 200000)   AND   (DEPT_NO IN (10, 20));

(SALARIO > 200000)   AND   ((DEPT_NO=10 OR  DEPT_NO=20))

/* Ejemplo de Aplicación 3 */

SELECT    NOMBRE_ALUMNO, NOTA1
FROM      NOTAS_ALUMNOS 
WHERE    (NOTA1=7)    AND    ((NOTA1+NOTA2+NOTA3)/3 >6);



/* Ejemplo de Aplicación 4 */

SELECT   APELLIDO
FROM     EMPLE
WHERE    (UPPER(APELLIDO)) LIKE 'J%';

/* Ejemplo de Aplicación 5 */

SELECT  APELLIDO
FROM    EMPLE
WHERE   UPPER(APELLIDO) LIKE '__R%';

/* Ejemplo de Aplicación 6 */

SELECT   APELLIDO
FROM      EMPLE
WHERE   UPPER(APELLIDO) LIKE 'A%O%';

/* Ejemplo de Aplicación 7 */

SELECT   APELLIDO,  SALARIO
FROM      EMPLE
WHERE    SALARIO BETWEEN  150000 AND 200000;

(SALARIO >=150000) AND (SALARIO<=200000)

/* Ejemplo de Aplicación 8 */

SELECT APELLIDO, SALARIO
FROM    EMPLE
WHERE   SALARIO  NOT   BETWEEN  150000 AND 200000;

(SALARIO <150000) OR (SALARIO>200000)

/* Ejemplo de Aplicación 9 */

SELECT   APELLIDO, OFICIO
FROM      EMPLE
WHERE    OFICIO IN('VENDEDOR', 'ANALISTA', 'EMPLEADO');

(OFICIO='VENDEDOR') OR (OFICIO='ANALISTA') OR (OFICIO='EMPLEADO')

/* Ejemplo de Aplicación 10 */

SELECT   APELLIDO, OFICIO
FROM      EMPLE
WHERE    OFICIO NOT IN('VENDEDOR', 'ANALISTA', 'EMPLEADO');

(OFICIO<>'VENDEDOR') AND (OFICIO<>'ANALISTA') AND (OFICIO!='EMPLEADO')





/* Ejemplo de Aplicación 11 */

SELECT APELLIDO , COMISION   
FROM   EMPLE    
WHERE  COMISION IS NULL;



/* Ejemplo de Aplicación 12 */

SELECT DISTINCT OFICIO
FROM EMPLE;

/* Ejemplo de Aplicación 13 */

SELECT   EMP_NO,  APELLIDO,  OFICIO,  DEPT_NO
FROM     EMPLE
WHERE    DEPT_NO=20
ORDER BY APELLIDO ASC, SALARIO DESC;

/* Ejemplo de Aplicación 14 */

SELECT   * 
FROM     EMPLE 
WHERE    OFICIO='ANALISTA'
ORDER BY EMP_NO ASC;

/* Ejemplo de Aplicación 15 */

SELECT    * 
FROM      EMPLE
WHERE     (DEPT_NO=20) AND (OFICIO='ANALISTA')
ORDER BY  APELLIDO DESC, EMP_NO DESC;

/* Ejemplo de Aplicación 16*/
SELECT APELLIDO, OFICIO, FECHA_ALT
FROM EMPLE
where fecha_alt between ('01/05/1981') and ('30/09/1981')
ORDER BY FECHA_ALT;



SELECT APELLIDO, OFICIO, FECHA_ALT
FROM EMPLE
WHERE (FECHA_ALT>='01/05/1981') AND (FECHA_ALT<='30/09/1981')
ORDER BY FECHA_ALT;