/* FUNCIONES */

/* Ejemplo de Aplicación 17*/

SELECT EMP_NO,APELLIDO,LENGTH(APELLIDO),INSTR(APELLIDO,'A') AS "POSICION A"
FROM EMPLE
WHERE UPPER(APELLIDO) LIKE '%Z';

WHERE SUBSTR(APELLIDO,-1,1)='Z';



/* Ejemplo de Aplicación 18*/

SELECT APELLIDO,SALARIO, MOD(SALARIO,550) AS RESTO
FROM EMPLE
WHERE OFICIO='VENDEDOR';

/* Ejemplo de Aplicación 19*/

SELECT APELLIDO,TRUNC((SYSDATE-FECHA_ALT)/7,0) AS "SEMANAS"
FROM EMPLE
WHERE DEPT_NO=10;

/* Ejemplo de Aplicación 20*/
SELECT EMP_NO,FECHA_ALT, ROUND(FECHA_ALT,'MONTH'),                                                                                                                                SELECT EMP_NO,FECHA_ALT,ROUND(FECHA_ALT, 'MONTH'),
TRUNC(FECHA_ALT,'MONTH')
FROM EMPLE
WHERE FECHA_ALT LIKE '%81';  

SELECT EMP_NO,FECHA_ALT,to_char(FECHA_ALT,'MONTH')
FROM EMPLE
WHERE EXTRACT(YEAR FROM FECHA_ALT)= 1981;  

 
SELECT EMP_NO,FECHA_ALT,to_char(FECHA_ALT,'MONTH'),
TRUNC(FECHA_ALT), round (fecha_ALT)
FROM EMPLE
WHERE EXTRACT(YEAR FROM FECHA_ALT)= 1981;    
							   
/* CONSULTAR MÁS DE UNA TABLA */


/* Ejemplo de Aplicación 21 */

SELECT EMP_NO, APELLIDO, OFICIO, DNOMBRE, LOC
FROM   EMPLE E, DEPART D
WHERE  E.DEPT_NO = D.DEPT_NO;

SELECT EMP_NO, APELLIDO, OFICIO, DNOMBRE, LOC
FROM   EMPLE natural join DEPART ;

select apellido,oficio,emp_no,dnombre,loc 
from emple join depart using(dept_no)

/* Ejemplo de Aplicación 22 */

SELECT E.*,LOC
FROM EMPLE E, DEPART D
WHERE (LOC IN ('MADRID', 'BARCELONA'))
AND (E.DEPT_NO=D.DEPT_NO);


SELECT E.apellido,d.LOC
FROM EMPLE E natural join DEPART D 
where loc='MADRID' or loc='BARCELONA'



SELECT E.apellido,d.LOC
FROM EMPLE E  join DEPART D using (dept_no)
where loc='MADRID' or loc='BARCELONA'

/* Ejemplo de Aplicación 23 */

SELECT E.EMP_NO AS "CODIGO EMPLEADO",
E.APELLIDO AS "Apellidos",
J.APELLIDO AS "SU JEFE ES..."
FROM EMPLE E, EMPLE J
WHERE J.EMP_NO=E.DIR;

SELECT E.EMP_NO AS "CODIGO EMPLEADO",
E.APELLIDO AS "Apellidos",
J.APELLIDO AS "SU JEFE ES..."
FROM EMPLE E join EMPLE J on J.EMP_NO=E.DIR;

/* Ejemplo de Aplicación 24 */

SELECT APELLIDO, OFICIO, LOC
FROM EMPLE E, DEPART D
WHERE OFICIO='ANALISTA' 
AND E.DEPT_NO = D.DEPT_NO;



SELECT APELLIDO,OFICIO, LOC
FROM EMPLE E NATURAL JOIN DEPART D
WHERE OFICIO='ANALISTA' 

/* Ejemplo de Aplicación 25 */

SELECT E.APELLIDO EMPLEADO, J.APELLIDO JEFE
FROM EMPLE E,EMPLE J
WHERE E.DIR=J.EMP_NO(+);

/* Ejemplo de Aplicación 26 */

SELECT D.DEPT_NO, DNOMBRE, APELLIDO
FROM EMPLE E,DEPART D
WHERE E.DEPT_NO(+)=D.DEPT_NO
ORDER BY D.DEPT_NO;

/* Ejemplo de Aplicación 27 */

SELECT DISTINCT OFICIO, LOC
FROM EMPLE E,DEPART D
WHERE E.DEPT_NO = D.DEPT_NO 
AND E.DEPT_NO=30;

SELECT   DISTINCT E.OFICIO, D.LOC
FROM EMPLE E NATURAL join DEPART D 
WHERE DEPT_NO=30




/* Ejemplo de Aplicación 28 */

SELECT E.APELLIDO, E.FECHA_ALT 
FROM EMPLE E CROSS JOIN EMPLE J
WHERE E.FECHA_ALT > J.FECHA_ALT AND J.APELLIDO='JIMENEZ';

SELECT E.APELLIDO, E.FECHA_ALT 
FROM EMPLE E JOIN EMPLE J
ON J.APELLIDO='JIMENEZ'
WHERE E.FECHA_ALT > J.FECHA_ALT;

SELECT E.APELLIDO, E.FECHA_ALT 
FROM EMPLE E , EMPLE J
WHERE J.APELLIDO='JIMENEZ' AND E.FECHA_ALT > J.FECHA_ALT;


SELECT APELLIDO,FECHA_ALT 
FROM EMPLE 
WHERE FECHA_ALT > (SELECT FECHA_ALT FROM EMPLE WHERE APELLIDO='JIMENEZ');









/* Ejemplo de Aplicación 29 */

SELECT E.APELLIDO AS EMPLEADO,E.FECHA_ALT AS "FECHA EMPLEADO",
J.APELLIDO AS JEFE, J.FECHA_ALT AS "FECHA JEFE"
FROM EMPLE E JOIN EMPLE J
ON J.EMP_NO = E.DIR
WHERE E.FECHA_ALT < J.FECHA_ALT;

SELECT E.APELLIDO AS EMPLEADO,E.FECHA_ALT AS "FECHA EMPLEADO",
J.APELLIDO AS JEFE, J.FECHA_ALT AS "FECHA JEFE"
FROM EMPLE E , EMPLE J
WHERE J.EMP_NO = E.DIR 
AND E.FECHA_ALT < J.FECHA_ALT;

/* Ejemplo aplicación 30 */

SELECT AVG(SALARIO) AS MEDIA, MAX(SALARIO) AS MAYOR, 
MIN(SALARIO) AS MENOR, SUM(SALARIO) AS SUMA
FROM EMPLE
WHERE OFICIO='VENDEDOR';

/* Ejemplo aplicación 31 */

SELECT  MAX(FECHA_ALT)AS "MENOR ANTIGÜEDAD", 
MIN(FECHA_ALT) AS "MAYOR ANTIGÜEDAD"
FROM EMPLE;

Para poder obtener el nombre del empleado de contratacion mas reciente
SELECT apellido, fecha_alt FROM EMPLE
 where fecha_alt= (select MAX(fecha_alt) from emple);

/* Ejemplo aplicación 32 */

SELECT  COUNT(*) "NUMERO DE EMPLEADOS"
FROM EMPLE
WHERE DEPT_NO=40;


/* Ejemplo aplicación 33*/

SELECT  COUNT(COMISION) AS "NºEMPLEADOS CON COMISION"
FROM EMPLE
WHERE DEPT_NO=30;


SELECT  COUNT(*) AS "NºEMPLEADOS CON COMISION"
FROM EMPLE
WHERE DEPT_NO=30 and COMISION>=0
					 COMISION IS NOT NULL;


 
/* Ejemplo aplicación 34*/

SELECT DEPT_NO, COUNT(*) "NUMERO DE EMPLEADOS"
FROM EMPLE
GROUP BY DEPT_NO;


/* Ejemplo aplicación 35*/

SELECT DEPT_NO, COUNT(*) "NÚMERO DE EMPLEADOS"
FROM EMPLE
GROUP BY DEPT_NO
HAVING COUNT(*) >4
ORDER BY COUNT(*) DESC;

SELECT  DNOMBRE, COUNT(EMP_NO) "NUMERO DE EMPLEADOS"
FROM DEPART D, EMPLE E
WHERE D.DEPT_NO=E.DEPT_NO
GROUP BY DNOMBRE
HAVING COUNT(*) >4;
			
SELECT D.DEPT_NO, DNOMBRE, COUNT(*) "NUMERO DE EMPLEADOS"
FROM DEPART D, EMPLE E
WHERE D.DEPT_NO=E.DEPT_NO
GROUP BY D.DEPT_NO,DNOMBRE
HAVING COUNT(*) >4;
