/*Ejercicio repaso*/
/*1*/
CREATE TABLE PROVINCIAS 
(COD_PROVI NUMBER(2) CONSTRAINT PRO_COD_PK PRIMARY KEY, 
NOMBRE VARCHAR2(25) CONSTRAINT PRO_NOM_NN NOT NULL, 
PAIS VARCHAR2(25) CONSTRAINT PRO_PAI_CH CHECK(PAIS = 'ESPAÑA' OR PAIS = 'PORTUGAL' OR PAIS = 'ITALIA')/*(PAIS IN ('ESPAÑA', 'PORTUGAL','ITALIA'))*/
);
/*2*/
DESC PROVINCIAS;
SELECT * FROM PROVINCIAS;
INSERT INTO PROVINCIAS VALUES(1, 'ALAVA', 'ESPAÑA');
/*3*/
TRUNCATE TABLE EMPRESAS;/*Borro pk me he equivocado*/
CREATE TABLE EMPRESAS(
COD_EMPRE NUMBER(2) CONSTRAINT EMP_COD_PK PRIMARY KEY,
NOMBRE VARCHAR(25) CONSTRAINT EMP_NOM_NN NOT NULL,
FECHA_CREA DATE DEFAULT(SYSDATE+1)/*Ojo, si metes null en este campo en el insert no pone la fecha*/
);
DESC EMPRESAS;
/*4*/
INSERT INTO EMPRESAS (COD_EMPRE, NOMBRE)VALUES(20, 'ARRIAGADAM S.A.');
SELECT * FROM EMPRESAS;
/*5*/
DROP TABLE CONTINENTES;
create table CONTINENTES(
COD_CONTI NUMBER CONSTRAINT CON_CON_PK PRIMARY KEY,
NOMBRE VARCHAR2(20) DEFAULT 'EUROPA' CONSTRAINT CON_NOM_NN NOT NULL,/*El default antes que el constraint, si no, da fallo*/
POBLACION NUMBER(10),
DENSIDAD NUMBER(3,1),
AREA NUMBER(8)
);/**/
DESC CONTINENTES;
/*6*/
SELECT * FROM CONTINENTES;
TRUNCATE TABLE CONTINENTES;
insert into CONTINENTES VALUES(1, 'ASIA', 3879000000, 88.5, 43810000);
insert into CONTINENTES VALUES(2, 'AMERICA', 910000000, 21.5, 42330000);
insert into CONTINENTES VALUES(3, 'AFRICA', 922011000, 30.4, 30370000);
insert into CONTINENTES (COD_CONTI, POBLACION, DENSIDAD,AREA) VALUES(4, 731000000, 71.8, 10180000);
insert into CONTINENTES VALUES(5, 'OCEANIA', 32000000, 4.2, 9008500);
/*7*/
CREATE TABLE EMPLEADOS(
COD_EMPLE NUMBER(2) CONSTRAINT EMP_COD_PR PRIMARY KEY,
NOMBRE VARCHAR2(20) CONSTRAINT EMR_NOM_NN NOT NULL,
APELLIDO VARCHAR2(25),
SALARIO NUMBER(7,2) CONSTRAINT EMP_SAL_CH CHECK(SALARIO>0),
COD_PROVI NUMBER(2) CONSTRAINT PRO_COD_FK REFERENCES PROVINCIAS ON DELETE CASCADE,
COD_EMPRE NUMBER(2) CONSTRAINT EMP_COD_FK REFERENCES EMPRESAS
);
/*8*/
ALTER TABLE EMPLEADOS ADD(HOBBY VARCHAR2(40), NHIJOS NUMBER(2));
DESC EMPLEADOS;
/*9*/
SELECT * FROM EMPLEADOS;
INSERT INTO EMPLEADOS VALUES()
