create table BLOQUESPISOS (
CALLE VARCHAR2(30),
NUMERO NUMBER(3),
PISO NUMBER(2),
PUERTA CHAR(1),
CODIGO_POSTAL NUMBER(5),
METROS NUMBER(5),
COMENTARIOS VARCHAR2(60),
COD_ZONA NUMBER(2),
DNI VARCHAR2(10),
CONSTRAINT BLO_CNPP_PK PRIMARY KEY (CALLE,NUMERO,PISO,PUERTA) 
);
DESC BLOQUESPISOS;
CREATE TABLE ZONAS(
COD_ZONA NUMBER(3) CONSTRAINT ZON_COD_PK PRIMARY KEY,
NOMBREZONA VARCHAR2(20),
MASDATOS VARCHAR2(50)
);
CREATE TABLE ALUMNOS(
DNI VARCHAR2(10) CONSTRAINT ALM_DNI_PK PRIMARY KEY,
NOMBRE VARCHAR2(30) NOT NULL,
EDAD NUMBER(2) CONSTRAINT ALM_EDA_CK CHECK(EDAD BETWEEN 5 AND 20),
CURSO NUMBER CONSTRAINT ALM_CUR_CK CHECK(CURSO IN(1,2,3))
);
CREATE TABLE PERSONAS(
DNI VARCHAR2(10) CONSTRAINT PER_DNI_PK PRIMARY KEY,
NOMBRE VARCHAR2(30),
DIRECCION VARCHAR2(30),
POBLACION VARCHAR2(30),
COD_PROV NUMBER(2) CONSTRAINT PER_COD_FK REFERENCES PROVINCPER

);
CREATE TABLE PROVINCPER(
COD_PROV NUMBER(2) CONSTRAINT PRP_COD_PK PRIMARY KEY,
NOM_PROV VARCHAR2(30)
);

INSERT INTO PROVINCPER VALUES(1,'ALAVA');
INSERT INTO PERSONAS VALUES('44686055E','INAKI','CALLE CUCHILL','VITORIA',01);
SELECT * FROM PERSONAS;
DELETE FROM PROVINCIAS WHERE COD_PROV= 1;
DELETE FROM PROVINCPER WHERE COD_PROV= 1;
ALTER TABLE PERSONAS DROP CONSTRAINT PER_COD_FK;
ALTER TABLE PERSONAS ADD CONSTRAINT PER_COP_FK FOREIGN KEY (COD_PROV) REFERENCES PROVINCPER ON DELETE CASCADE;
DROP TABLE PROVINCPER CASCADE CONSTRAINTS;