/*REPASO EJERCICIOS UD7 EN CASA*/
/*1*/
CREATE TABLE NOTAS_ALUMNOS
(
  NOMBRE_ALUMNO    VARCHAR2(25) PRIMARY KEY,
  NOTA1 NUMBER(2),
  NOTA2 NUMBER(2),
  NOTA3 NUMBER(2));
  
INSERT INTO NOTAS_ALUMNOS VALUES('Alcalde Garc�a, Elena', 5,5,5);
INSERT INTO NOTAS_ALUMNOS VALUES('Benito Mart�n, Luis', 7,6,8);
INSERT INTO NOTAS_ALUMNOS VALUES('Casas Martinez, Manuel', 7,5,5);
INSERT INTO NOTAS_ALUMNOS VALUES('Corregidor Sanchez,Ana',6,9,8);
SELECT * FROM NOTAS_ALUMNOS;

SELECT NOMBRE_ALUMNO AS "NOMBRE DEL ALUMNO", ROUND(((NOTA1+NOTA2+NOTA3)/3),2) AS "NOTA MEDIA" 
FROM NOTAS_ALUMNOS;
/*2*/
SELECT * FROM EMPLE;
SELECT APELLIDO, SALARIO, DEPT_NO FROM EMPLE WHERE SALARIO>200000 AND DEPT_NO IN (10, 20);

DROP TABLE DEPART CASCADE CONSTRAINTS; 
CREATE TABLE DEPART (
 	DEPT_NO  NUMBER(2) CONSTRAINT DEP_PK PRIMARY KEY,
	DNOMBRE  VARCHAR2(14), 
 	LOC      VARCHAR2(14));
  
INSERT INTO DEPART VALUES (10,'CONTABILIDAD','SEVILLA');
INSERT INTO DEPART VALUES (20,'INVESTIGACION','MADRID');
INSERT INTO DEPART VALUES (30,'VENTAS','BARCELONA');
INSERT INTO DEPART VALUES (40,'PRODUCCION','BILBAO');

COMMIT;
DROP TABLE EMPLE CASCADE CONSTRAINTS; 

CREATE TABLE EMPLE (
 	EMP_NO    NUMBER(4) CONSTRAINT EMP_PK PRIMARY KEY,
 	APELLIDO  VARCHAR2(10),
 	OFICIO    VARCHAR2(10),
 	DIR       NUMBER(4) CONSTRAINT EMP_DIR_FK  REFERENCES EMPLE ON DELETE SET NULL,
 	FECHA_ALT DATE,
 	SALARIO   NUMBER(10),
 	COMISION  NUMBER(10),
 	DEPT_NO   NUMBER(2) NOT NULL CONSTRAINT EMP_DEP_FK 	REFERENCES DEPART ON DELETE CASCADE);
  
  
INSERT INTO EMPLE VALUES (7839,'REY','PRESIDENTE',NULL,'17/12/1981',650000,NULL,10);
INSERT INTO EMPLE VALUES (7566,'JIMENEZ','DIRECTOR',7839,'02/04/1981',386750,NULL,20);
INSERT INTO EMPLE VALUES (7698,'NEGRO','DIRECTOR',7839,'01/05/1981',370500,NULL,30);
INSERT INTO EMPLE VALUES (7782,'CEREZO','DIRECTOR',7839,'09/06/1981',318500,NULL,10);
INSERT INTO EMPLE VALUES (7788,'GIL','ANALISTA',7566,'09/11/1981',390000,NULL,20);
INSERT INTO EMPLE VALUES (7902,'FERNANDEZ','ANALISTA',7566,'03/12/1981',390000,NULL,20);
INSERT INTO EMPLE VALUES (7499,'ARROYO','VENDEDOR',7698,'20/02/1980',208000,39000,30);
INSERT INTO EMPLE VALUES (7521,'SALA','VENDEDOR',7698,'22/02/1981',162500,65000,30);
INSERT INTO EMPLE VALUES (7654,'MARTIN','VENDEDOR',7698,'29/09/1981',162500,182000,30);
INSERT INTO EMPLE VALUES (7844,'TOVAR','VENDEDOR',7698,'08/09/1981',195000,0,30);
INSERT INTO EMPLE VALUES (7900,'JIMENO','EMPLEADO',7698,'03/12/1981',123500,NULL,30);
INSERT INTO EMPLE VALUES (7369,'SANCHEZ','EMPLEADO',7902,'17/12/1980',104000,NULL,20);
INSERT INTO EMPLE VALUES (7876,'ALONSO','EMPLEADO',7788,'23/09/1981',143000,NULL,20);
INSERT INTO EMPLE VALUES (7934,'MU�OZ','EMPLEADO',7782,'23/01/1982',169000,NULL,10);

SELECT APELLIDO, SALARIO, DEPT_NO FROM EMPLE WHERE SALARIO>200000 AND DEPT_NO IN(10,20);

/*3*/
SELECT * FROM NOTAS_ALUMNOS;
SELECT NOMBRE_ALUMNO FROM NOTAS_ALUMNOS WHERE NOTA1 = 7 AND ((NOTA1+NOTA2+NOTA3)/3)>6;
/*4*/
SELECT * FROM EMPLE;
SELECT APELLIDO FROM EMPLE WHERE (UPPER(APELLIDO)) LIKE 'J%';
/*5*/
SELECT APELLIDO FROM EMPLE WHERE (UPPER(APELLIDO)) LIKE '_R%';
/*6*/
SELECT APELLIDO FROM EMPLE WHERE (UPPER(APELLIDO)) LIKE 'A%O%';
/*7*/
SELECT APELLIDO, SALARIO FROM EMPLE WHERE SALARIO BETWEEN 150000 AND 200000;
/*8*/
SELECT APELLIDO, SALARIO FROM EMPLE WHERE SALARIO NOT BETWEEN 150000 AND 200000;
/*9*/
SELECT APELLIDO, OFICIO FROM EMPLE WHERE OFICIO IN ('VENDEDOR', 'ANALISTA','EMPLEADO');
/*10*/
SELECT APELLIDO, OFICIO FROM EMPLE WHERE OFICIO NOT IN ('VENDEDOR', 'ANALISTA','EMPLEADO');
/*11*/
SELECT APELLIDO, COMISION FROM EMPLE WHERE COMISION IS NULL;
/*12*/
SELECT DISTINCT OFICIO FROM EMPLE;
/*13*/
SELECT EMP_NO, APELLIDO, OFICIO, DEPT_NO FROM EMPLE WHERE DEPT_NO=20 ORDER BY APELLIDO, SALARIO DESC;
/*14*/
SELECT EMP_NO, APELLIDO FROM EMPLE WHERE OFICIO LIKE 'ANALISTA' ORDER BY EMP_NO;
/*15*/
SELECT APELLIDO, EMP_NO FROM EMPLE WHERE DEPT_NO=20 AND OFICIO LIKE 'ANALISTA' ORDER BY APELLIDO DESC, EMP_NO DESC;
/*16*/
SELECT APELLIDO, OFICIO, FECHA_ALT FROM EMPLE WHERE FECHA_ALT BETWEEN '01/05/81' AND '30/09/81'ORDER BY FECHA_ALT;
/*17*/
SELECT EMP_NO, APELLIDO, LENGTH(APELLIDO)AS LONGITUDAPELLIDO, INSTR(APELLIDO, 'A') AS POSICION 
FROM EMPLE WHERE APELLIDO LIKE '%Z';
/*18*/
SELECT MOD(SALARIO, 550) FROM EMPLE WHERE OFICIO LIKE 'VENDEDOR';
/*19*/
SELECT APELLIDO, TRUNC((SYSDATE-FECHA_ALT)/7,1) AS SEMANAS FROM EMPLE WHERE DEPT_NO=10;
/*20*/
SELECT EMP_NO, FECHA_ALT, EXTRACT(MONTH FROM FECHA_ALT) FROM EMPLE WHERE EXTRACT(YEAR FROM FECHA_ALT)=1981;
SELECT EMP_NO, FECHA_ALT, ROUND(FECHA_ALT, 'MONTH'), TRUNC(FECHA_ALT, 'MONTH') FROM EMPLE WHERE EXTRACT(YEAR FROM FECHA_ALT)=1981;
/*21*/
SELECT APELLIDO, OFICIO, EMP_NO, DNOMBRE, LOC FROM EMPLE, DEPART WHERE EMPLE.DEPT_NO= DEPART.DEPT_NO;
/*22*/
SELECT APELLIDO, OFICIO, EMP_NO, DNOMBRE, LOC FROM EMPLE, DEPART WHERE EMPLE.DEPT_NO= DEPART.DEPT_NO AND LOC IN('MADRID', 'BARCELONA');
/*23*/
SELECT * FROM EMPLE;

SELECT E.EMP_NO, E.APELLIDO, J.APELLIDO 
FROM EMPLE E, EMPLE J 
WHERE E.DIR=J.EMP_NO;
/*24*/
SELECT APELLIDO, OFICIO, LOC 
FROM EMPLE, DEPART 
WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO AND OFICIO='ANALISTA';
/*25*/
SELECT E.APELLIDO AS CURRELA, J.APELLIDO AS "SU JEFE" 
FROM EMPLE E, EMPLE J 
WHERE E.DIR=J.EMP_NO(+);
/*26*/
SELECT APELLIDO, DNOMBRE FROM EMPLE E, DEPART D WHERE E.DEPT_NO(+)=D.DEPT_NO;
/*27*/
SELECT OFICIO, LOC FROM EMPLE E, DEPART D 
WHERE E.DEPT_NO=30 AND E.DEPT_NO=D.DEPT_NO;
/*28*/
SELECT APELLIDO, FECHA_ALT 
FROM EMPLE 
WHERE FECHA_ALT>(SELECT FECHA_ALT FROM EMPLE WHERE APELLIDO LIKE 'JIMENEZ');
/*29*/
SELECT E.APELLIDO EMPLEADO, E.FECHA_ALT , D.APELLIDO DIRECTOR, D.FECHA_ALT
FROM EMPLE E, EMPLE D WHERE E.DIR=D.EMP_NO AND E.FECHA_ALT<D.FECHA_ALT;
/*30*/
SELECT AVG(SALARIO), MAX(SALARIO), MIN(SALARIO), SUM(SALARIO) FROM EMPLE WHERE OFICIO LIKE 'VENDEDOR';
/*31*/
SELECT MIN(FECHA_ALT), MAX(FECHA_ALT) FROM EMPLE; 
/*32*/
SELECT COUNT(*) FROM EMPLE WHERE DEPT_NO=40;
/*33*/
SELECT COUNT(*) FROM EMPLE WHERE COMISION IS NOT NULL;
/*34*/
SELECT DEPT_NO, COUNT(*) FROM EMPLE GROUP BY DEPT_NO;
/*35*/
SELECT DEPT_NO, COUNT(*) 
FROM EMPLE 
GROUP BY DEPT_NO 
HAVING COUNT(*)>4 ORDER BY COUNT(*) DESC;
/*36*/
SELECT DEPT_NO, OFICIO, COUNT(*) 
FROM EMPLE 
GROUP BY OFICIO, DEPT_NO 
ORDER BY DEPT_NO;
/*37*/
SELECT MAX(COUNT(*))
FROM EMPLE 
GROUP BY DEPT_NO;
/*38*/
SELECT D.DEPT_NO, D.DNOMBRE, COUNT(EMP_NO) 
FROM EMPLE E, DEPART D 
WHERE E.DEPT_NO(+)=D.DEPT_NO
GROUP BY E.DEPT_NO,D.DEPT_NO, D.DNOMBRE;
/*39*/
SELECT DEPT_NO, ROUND(AVG(SALARIO),2) 
FROM EMPLE 
GROUP BY DEPT_NO
HAVING MAX(SALARIO)>250000 ;
/*40*/
SELECT MAX(ROUND(AVG(SALARIO),1)) 
FROM EMPLE 
GROUP BY DEPT_NO;
/*41*/
SELECT OFICIO, COUNT(*) 
FROM EMPLE 
GROUP BY OFICIO;
/*42*/
SELECT DIR, MIN(SALARIO) 
FROM EMPLE
WHERE DIR IS NOT NULL 
GROUP BY DIR
HAVING MIN(SALARIO)>200000 
ORDER BY MIN(SALARIO) DESC;
/*43*/
SELECT DNOMBRE, LOC, COUNT(EMP_NO), ROUND(AVG(SALARIO),2)
FROM DEPART D, EMPLE E 
WHERE E.DEPT_NO=D.DEPT_NO
GROUP BY DNOMBRE, LOC;
/*44*/
SELECT COUNT(*) 
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO=D.DEPT_NO AND DNOMBRE LIKE 'VENTAS' AND OFICIO 
LIKE 'VENDEDOR';
/*45*/
SELECT SUM(SALARIO) 
FROM EMPLE, DEPART 
WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO AND DNOMBRE = 'VENTAS' 
GROUP BY OFICIO;
/*46*/
SELECT COUNT(*) 
FROM EMPLE 
WHERE OFICIO LIKE 'EMPLEADO' 
GROUP BY DEPT_NO;
/*47*/
SELECT DEPT_NO 
FROM EMPLE 
GROUP BY DEPT_NO, OFICIO
HAVING COUNT(*)>2;
/*48*/
SELECT APELLIDO,OFICIO 
FROM EMPLE 
WHERE OFICIO LIKE(SELECT OFICIO FROM EMPLE WHERE APELLIDO='GIL')
AND APELLIDO NOT LIKE 'GIL';
/*51*/
SELECT APELLIDO, DEPT_NO, SALARIO 
FROM EMPLE 
WHERE (DEPT_NO, SALARIO) IN (SELECT DEPT_NO, SALARIO FROM EMPLE WHERE COMISION IS NOT NULL);
/*52*/
SELECT E.APELLIDO, D.DNOMBRE, E.SALARIO 
FROM EMPLE E, DEPART D 
WHERE E.DEPT_NO=D.DEPT_NO AND (SALARIO, COMISION) 
IN (SELECT SALARIO, COMISION FROM EMPLE E, DEPART D WHERE E.DEPT_NO=D.DEPT_NO AND D.DNOMBRE='BARCELONA');
/*53*/
SELECT EMP_NO, APELLIDO, DEPT_NO 
FROM EMPLE 
WHERE DEPT_NO IN (SELECT DEPT_NO FROM DEPART WHERE LOC LIKE '%A');
/*54*/
SELECT EMP_NO, SALARIO 
FROM EMPLE 
WHERE SALARIO > ALL(SELECT J.SALARIO FROM EMPLE E, EMPLE J WHERE E.EMP_NO=J.DIR);
/*55*/
SELECT APELLIDO, EMP_NO FROM EMPLE E, EMPLE MEDIA WHERE E.DEPT_NO=MEDIA.DEPT_NO SALARIO, DEPT_NO) (SELECT );
/*56*/
SELECT EMP_NO, APELLIDO 
FROM EMPLE 
WHERE SALARIO >ALL(SELECT SALARIO FROM EMPLE WHERE OFICIO='DIRECTOR');
/*57*/
SELECT APELLIDO
FROM EMPLE E
WHERE NOT EXISTS (SELECT * 
                        FROM EMPLE S WHERE S.EMP_NO=E.DIR);
/*58*/
select * from emple;
SELECT LEVEL, APELLIDO 
FROM EMPLE 
START WITH APELLIDO='JIMENO' 
CONNECT BY PRIOR DIR=EMP_NO;
/*59*/
SELECT * FROM EMPLE;
SELECT DEPT_NO 
FROM DEPART 
MINUS 
SELECT DEPT_NO 
FROM EMPLE
WHERE OFICIO LIKE 'ANALISTA';

select E.APELLIDO, E.SALARIO, E.DEPT_NO, S.SALMEDIO 
FROM EMPLE E, (SELECT DEPT_NO, AVG(SALARIO) SALMEDIO FROM EMPLE GROUP BY DEPT_NO) S
WHERE E.DEPT_NO=S.DEPT_NO AND E.SALARIO>S.SALMEDIO
ORDER BY SALMEDIO DESC;