/*EJ 1*/
create table PROVINCIAS(
COD_PROV NUMBER(2) CONSTRAINT PRO_COD_PK PRIMARY KEY,
NOMBRE VARCHAR2(25) CONSTRAINT PRO_NOM_NN NOT NULL,
PAIS VARCHAR2(25) CONSTRAINT PRO_PAI_CH CHECK(PAIS IN('ESPAÑA','PORTUGAL','ITALIA'))
);
DESC PROVINCIAS;
SELECT * FROM SYS.USER_CONSTRAINTS WHERE TABLE_NAME='PROVINCIAS';
/*EJ 2*/
INSERT INTO PROVINCIAS VALUES(1,'ALAVA', 'ESPAÑA');
SELECT * FROM PROVINCIAS;
/*EJ 3*/
CREATE TABLE EMPRESAS (
COD_EMPRE NUMBER(2) CONSTRAINT EMP_COD_PK PRIMARY KEY,
NOMBRE VARCHAR(2) NOT NULL,
FECHA_CREA DATE DEFAULT SYSDATE + 1
);
DESC EMPRESAS;
ALTER TABLE EMPRESAS MODIFY (NOMBRE VARCHAR2(25));
/*EJ 4*/
INSERT INTO EMPRESAS(COD_EMPRE, NOMBRE) VALUES (20,'ARRIAGADAMS.A.');
SELECT * FROM EMPRESAS;
/*5*/
CREATE TABLE CONTINENTES(
COD_CONTI NUMBER(2) CONSTRAINT CONT_COD_PK PRIMARY KEY,
NOMBRE VARCHAR2(20) DEFAULT 'EUROPA' CONSTRAINT CONT_NOM_NN NOT NULL,
POBLACION NUMBER(10),
DENSIDAD NUMBER(3,1),
AREA NUMBER(8)
);
/*6*/
INSERT INTO CONTINENTES VALUES(1,'ASIA',3879000000,88.5,43810000);
INSERT INTO CONTINENTES VALUES(2,'AMERICA',91000000,21.5,42330000);
INSERT INTO CONTINENTES VALUES(3,'AFRICA',922011000,30.4,30370000);
INSERT INTO CONTINENTES VALUES(4,'EUROPA',387900000,71.8,10181000);
INSERT INTO CONTINENTES VALUES(5,'OCEANIA',3200000,4.2,9008500);
/*7*/
DROP TABLE EMPLEADOS;
CREATE TABLE EMPLEADOS(
COD_EMPLE NUMBER(2) CONSTRAINT EMP_CEM_PK PRIMARY KEY,
NOMBRE VARCHAR2(20) NOT NULL,
APELLIDO VARCHAR2(25),
SALARIO NUMBER(7,2) CONSTRAINT EMP_SAL_CH CHECK(SALARIO>0),
PROVINCIA NUMBER(2) CONSTRAINT EMP_PRO_FK REFERENCES PROVINCIAS ON DELETE CASCADE,
COD_EMPRE NUMBER(2),
CONSTRAINT EMP_EPR_FK FOREIGN KEY (COD_EMPRE) REFERENCES EMPRESAS
);
/*8*/
DESC EMPLEADOS;
ALTER TABLE EMPLEADOS ADD (HOBBY VARCHAR2(40), NHIJOS NUMBER(2));
/*9*/
INSERT INTO EMPLEADOS VALUES(1,'INAKI','DIAZ',1200,1,20,'NAVEGAR',0);
SELECT * FROM EMPLEADOS;
/*10*/
ALTER TABLE EMPLEADOS ADD(EDAD NUMBER(3) NOT NULL);
/*11*/
ALTER TABLE EMPLEADOS ADD(EDAD NUMBER(3) DEFAULT 000 NOT NULL);
/*12*/
ALTER TABLE EMPLEADOS DROP (EDAD, NHIJOS);
/*13*/
ALTER TABLE EMPLEADOS MODIFY(HOBBY VARCHAR2(30));
/*14*/
ALTER TABLE EMPLEADOS ADD CONSTRAINT EMP_SAL_CK CHECK (SALARIO BETWEEN 1000 AND 4000);
SELECT * FROM SYS.USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLEADOS';
ALTER TABLE EMPLEADOS RENAME CONSTRAINT EMP_SAL_CK TO SALARIORANGO;
/*15*/
CREATE TABLE INDUSTRIAS AS SELECT * FROM EMPRESAS;
SELECT * FROM INDUSTRIAS;
/*16*/
/*17*/
DELETE FROM EMPLEADOS WHERE NOMBRE='INAKI' AND APELLIDO='DIAZ';
/*18*/
SELECT * FROM CONTINENTES;
UPDATE CONTINENTES SET POBLACION = POBLACION + 1000 WHERE DENSIDAD<30 ;
UPDATE CONTINENTES SET DENSIDAD = (SELECT DENSIDAD FROM CONTINENTES WHERE NOMBRE = 'AFRICA') WHERE AREA < 20000000; 
UPDATE CONTINENTES SET DENSIDAD = DENSIDAD + 2 WHERE POBLACION>(SELECT POBLACION FROM CONTINENTES WHERE NOMBRE ='AMERICA');

DELETE FROM CONTINENTES;