/*EJERCICIO 1*/
CREATE VIEW EMP_30 AS 
SELECT EMP_NO, APELLIDO, SALARIO, DEPT_NO 
FROM EMPLE 
WHERE DEPT_NO=30;
/*EJERCICIO 2*/
SELECT * FROM EMP_30;
SELECT * FROM EMPLE;
INSERT INTO EMPLE VALUES(7777, 'PEPE','ANALISTA', 7698, NULL, 200000, NULL, 30 );
/*3*/
INSERT INTO EMP_30 VALUES(0001, 'ENLAVISTA2', 200001, 30);
INSERT INTO EMP_30 VALUES(0000, 'ENLAVISTA', 200001, 10);
/*4*/
CREATE OR REPLACE VIEW EMP_30 AS
SELECT EMP_NO, APELLIDO, SALARIO, DEPT_NO 
FROM EMPLE 
WHERE DEPT_NO=30 
WITH CHECK OPTION CONSTRAINT EM30_CK;
INSERT INTO EMP_30 VALUES(1111,'LOPEZ',1200, 30);
INSERT INTO EMP_30 VALUES(2222,'RUIZ',2200, 20);
/*5*/
CREATE VIEW SAL_20 AS 
SELECT EMP_NO AS ID_EMP, APELLIDO AS APE_EMP, SALARIO*12 AS SAL_ANUAL 
FROM EMPLE 
WHERE DEPT_NO=20;
SELECT * FROM SAL_20;
/*6*/
CREATE OR REPLACE VIEW DEPT_SUM(NOMBRE_DEPARTAMENTO, SALARIOS_MINIMOS, SALARIOS_MAXIMOS, SALARIOS_MEDIOS) AS 
SELECT D.DNOMBRE, MIN(E.SALARIO), MAX(E.SALARIO), TRUNC(AVG(E.SALARIO),0)
FROM EMPLE E, DEPART D
WHERE E.DEPT_NO=D.DEPT_NO
GROUP BY D.DNOMBRE;
SELECT * FROM DEPT_SUM;
/*7*/
DROP VIEW DEPT_SUM;