/* VISTAS */

/* Ejemplo de Aplicación 1 */

DROP VIEW EMP_30;

CREATE  OR REPLACE VIEW EMP_30
AS 
SELECT  EMP_NO, APELLIDO, SALARIO, DEPT_NO
FROM    EMPLE
WHERE   DEPT_NO=30;

DESCRIBE EMP_30;
SELECT * FROM EMP_30;

/* Ejemplo de Aplicación 2 */

SELECT * FROM EMP_30;

INSERT INTO EMPLE VALUES(0000,'PEPE','ANALISTA',7698,NULL,200000,NULL,30);

SELECT * FROM EMP_30;



/* Ejemplo de Aplicación 3 */

INSERT INTO EMP_30 VALUES(8888,'RUIZ',280000,30);

/* lo inserta en la tabla y en la vista */

SELECT * FROM EMPLE;
SELECT * FROM EMP_30;

INSERT INTO EMP_30 VALUES(8887,'PEPE',580000,10);

SELECT * FROM EMPLE;
SELECT * FROM EMP_30;
/* lo inserta sólo en la tabla */

/* Ejemplo de Aplicación 4 */

CREATE OR REPLACE  VIEW EMP_30
AS SELECT  EMP_NO, APELLIDO, SALARIO, DEPT_NO
   FROM    EMPLE
   WHERE   DEPT_NO=30
   WITH CHECK OPTION CONSTRAINT EMP30_ERROR;  

SELECT * FROM EMP_30;

INSERT INTO EMP_30 VALUES (1111, 'LOPEZ', 1200,30);  
INSERT INTO EMP_30 VALUES (2222, 'RUIZ', 2200,20);  

/* ERROR en línea 1:
ORA-01402: violación de la cláusula WHERE en la vista WITH CHECK OPTION */

UPDATE EMP_30 SET DEPT_NO=10 
WHERE EMP_NO= 7698;

/* ERROR en línea 1:
ORA-01402: violación de la cláusula WHERE en la vista WITH CHECK OPTION */

/* Ejemplo de Aplicación 5 */

DROP VIEW SAL_20;

CREATE VIEW SAL_20
AS SELECT  EMP_NO AS ID_EMP, APELLIDO AS APE_EMP,SALARIO*12 AS SAL_ANUAL
   FROM    EMPLE
   WHERE   DEPT_NO= 20;

/* otra alternativa */

CREATE VIEW SAL_20(ID_EMP, APE_EMP, SAL_ANUAL)
AS SELECT  EMP_NO, APELLIDO ,SALARIO*12 
   FROM    EMPLE
   WHERE   DEPT_NO= 20;
   

   
/* Ejemplo de Aplicación 6 */

DROP VIEW DEPT_SUM;

CREATE VIEW DEPT_SUM(DEPT_NOMBRE, SAL_MIN, SAL_MAX, SAL_MED)
AS SELECT  DNOMBRE, MIN(SALARIO), MAX(SALARIO), TRUNC(AVG(SALARIO),0)
   FROM    EMPLE E, DEPART D
   WHERE   E.DEPT_NO=D.DEPT_NO
   GROUP BY DNOMBRE;  

/* Ejemplo de Aplicación 7 */
   
DROP VIEW SAL_20;