/* EJERCICIO 11 */

DROP TABLE EMPLEADO CASCADE CONSTRAINTS; 

CREATE TABLE EMPLEADO (
 EMP_NO    NUMBER(4) NOT NULL,
 APELLIDO  VARCHAR2(10)  ,
 OFICIO    VARCHAR2(10)  ,
 DIR       NUMBER(4) ,
 FECHA_ALT DATE      ,
 SALARIO   NUMBER(10),
 COMISION  NUMBER(10),
 DEPT_NO   NUMBER(2) NOT NULL);


ALTER  TABLE  EMPLEADO  ADD CONSTRAINT EMP_APE_UK  UNIQUE(apellido); 

ALTER TABLE EMPLEADO ADD CONSTRAINT EMP_COM_NN NOT NULL(COMISION); 
/*ERROR en línea 1:
ORA-00904: : identificador no válido*/

/* Dos formas de hacer lo mismo: */

ALTER TABLE EMPLEADO MODIFY COMISION NOT NULL;
ALTER TABLE EMPLEADO ADD CONSTRAINT EMP_COM_NN 
CHECK(COMISION IS NOT NULL); 



ALTER TABLE EMPLEADO ADD CONSTRAINT EMP_APE_NN 
CHECK(APELLIDO IS NOT NULL); 
ALTER TABLE EMPLEADO MODIFY APELLIDO NOT NULL;


/* EJERCICIO 12 */

SELECT CONSTRAINT_NAME 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME='EMPLEADO'; 

ALTER TABLE EMPLEADO
DROP CONSTRAINT SYS_C004090;

/* dos formas de hacerlo: */
ALTER TABLE EMPLEADO 
DROP CONSTRAINT EMP_APE_UK;

ALTER TABLE EMPLEADO 
DROP UNIQUE(APELLIDO);


/* EJERCICIO 13 */
Lo primero pongo ambos campos con igual tipo de datos
ALTER TABLE BLOQUESPISOS MODIFY COD_ZONA VARCHAR(3);

ALTER TABLE BLOQUESPISOS 
ADD CONSTRAINT BLO_ZON_FK FOREIGN KEY (COD_ZONA) 
REFERENCES ZONAS ON DELETE SET NULL;

ALTER TABLE ZONAS DROP PRIMARY KEY;
/* ERROR en línea 1:
ORA-02273: a esta clave única/primaria hacen referencia algunas claves ajenas */

ALTER TABLE ZONAS DROP PRIMARY KEY CASCADE;


/* EJERCICIO 14 */

SELECT  CONSTRAINT_NAME, TABLE_NAME, CONSTRAINT_TYPE 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='ALUMNOS';

/* EJERCICIO 15 */

SELECT CONSTRAINT_NAME, TABLE_NAME, COLUMN_NAME, POSITION 
FROM USER_CONS_COLUMNS  
WHERE TABLE_NAME ='BLOQUESPISOS' OR TABLE_NAME ='ZONAS';


/* where TABLE_NAME  in ('BLOQUESPISOS' ,'ZONAS') */


/* EJERCICIO 16 */

SELECT TABLE_NAME, TABLESPACE_NAME
FROM USER_TABLES;












/* EJERCICIO 17 */

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME IN ('PROVINCIAS', 'PERSONAS');

/* WHERE TABLE_NAME='PROVINCIAS'  OR TABLE_NAME='PERSONAS' */

RENAME PERSONAS TO CIUDADANOS;

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME IN ('PROVINCIAS', 'CIUDADANOS');

/* Se mantienen las mismas restricciones al renombrar la tabla. */

/* EJERCICIO 18 */

TRUNCATE TABLE ALUMNOS;

DELETE FROM ALUMNOS;













/* EJERCICIO 19*/

/* ******** TABLA DEPART: *********** */

DROP TABLE DEPART CASCADE CONSTRAINTS; 

CREATE TABLE DEPART (
 	DEPT_NO  NUMBER(2) CONSTRAINT DEP_PK PRIMARY KEY,
	DNOMBRE  VARCHAR2(14), 
 	LOC      VARCHAR2(14));
	
 
INSERT INTO DEPART VALUES (10,'CONTABILIDAD','SEVILLA');
INSERT INTO DEPART VALUES (20,'INVESTIGACION','MADRID');
INSERT INTO DEPART VALUES (30,'VENTAS','BARCELONA');
INSERT INTO DEPART VALUES (40,'PRODUCCION','BILBAO');

COMMIT;

/*  ******** TABLA EMPLE: ************* */

DROP TABLE EMPLE CASCADE CONSTRAINTS; 

CREATE TABLE EMPLE (
 	EMP_NO    NUMBER(4) CONSTRAINT EMP_PK PRIMARY KEY,
 	APELLIDO  VARCHAR2(10),
 	OFICIO    VARCHAR2(10),
 	DIR       NUMBER(4) CONSTRAINT EMP_DIR_FK 
						REFERENCES EMPLE ON DELETE SET NULL,
 	FECHA_ALT DATE,
 	SALARIO   NUMBER(10),
 	COMISION  NUMBER(10),
 	DEPT_NO   NUMBER(2) NOT NULL 
						CONSTRAINT EMP_DEP_FK 
						REFERENCES DEPART ON DELETE CASCADE);
						
						
						
						
						
						
INSERT INTO EMPLE VALUES (7839,'REY','PRESIDENTE',NULL,'17/12/1981',650000,NULL,10);
INSERT INTO EMPLE VALUES (7566,'JIMENEZ','DIRECTOR',7839,'02/04/1981',386750,NULL,20);
INSERT INTO EMPLE VALUES (7698,'NEGRO','DIRECTOR',7839,'01/05/1981',370500,NULL,30);
INSERT INTO EMPLE VALUES (7782,'CEREZO','DIRECTOR',7839,'09/06/1981',318500,NULL,10);
INSERT INTO EMPLE VALUES (7788,'GIL','ANALISTA',7566,'09/11/1981',390000,NULL,20);
INSERT INTO EMPLE VALUES (7902,'FERNANDEZ','ANALISTA',7566,'03/12/1981',390000,NULL,20);
INSERT INTO EMPLE VALUES (7499,'ARROYO','VENDEDOR',7698,'20/02/1980',208000,39000,30);
INSERT INTO EMPLE VALUES (7521,'SALA','VENDEDOR',7698,'22/02/1981',162500,65000,30);
INSERT INTO EMPLE VALUES (7654,'MARTIN','VENDEDOR',7698,'29/09/1981',162500,182000,30);
INSERT INTO EMPLE VALUES (7844,'TOVAR','VENDEDOR',7698,'08/09/1981',195000,0,30);
INSERT INTO EMPLE VALUES (7900,'JIMENO','EMPLEADO',7698,'03/12/1981',123500,NULL,30);
INSERT INTO EMPLE VALUES (7369,'SANCHEZ','EMPLEADO',7902,'17/12/1980',104000,NULL,20);
INSERT INTO EMPLE VALUES (7876,'ALONSO','EMPLEADO',7788,'23/09/1981',143000,NULL,20);
INSERT INTO EMPLE VALUES (7934,'MUÑOZ','EMPLEADO',7782,'23/01/1982',169000,NULL,10);
